- name: Ensure we can become root
  become: true
  command: "echo 'Test'"
  changed_when: false

- name: Install classic packages
  become: true
  apt:
    name:
      - fail2ban
      - vim
      - sudo
      - mosh
      - borgbackup
      - htop
      # Includes iostat
      - sysstat
      - iotop
      - iftop
      - unattended-upgrades
      # Includes dig
      - dnsutils
      - curl
    state: present

- name: Configure sshd
  become: true
  import_tasks: ssh.yml

- name: Install and configure netdata
  import_tasks: netdata.yml
  tags: netdata
