- name: Ensure group ssh exists
  group:
    name: ssh
    state: present

- name: Add users to ssh group
  user:
    groups: ssh
    name: "{{ item }}"
    append: true
  loop:
    - root
    - "{{ ansible_user_id }}"

- name: Configure sshd
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      # Crypto hardening
      # Based on https://stribika.github.io/2015/01/04/secure-secure-shell.html
      # And https://tls.imirhil.fr/ssh
      Protocol 2
      HostKey /etc/ssh/ssh_host_ed25519_key
      KexAlgorithms curve25519-sha256@libssh.org
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

      # Restrict access to the ssh group
      AllowGroups ssh

      # PasswordAuthentication no
      # ChallengeResponseAuthentication no
    validate: "/usr/sbin/sshd -T -f %s"
  notify: Restart sshd

